component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./conf/.*
- ./conf/testng/.*
- ./doc/.*
- ./doc/bugs/.*
- ./doc/design/.*
- ./doc/manual/.*
- ./doc/manual/en/.*
- ./doc/manual/en/images/.*
- ./doc/manual/en/modules/.*
- ./doc/tests/.*
- ./doc/tutorial/.*
- ./doc/tutorial/en/.*
- ./doc/tutorial/en/code/.*
- ./doc/tutorial/en/images/.*
- ./doc/tutorial/en/modules/.*
- ./eclipse-classes/.*
- ./eclipse-classes/org/.*
- ./eclipse-classes/org/jgroups/.*
- ./eclipse-classes/org/jgroups/annotations/.*
- ./eclipse-classes/org/jgroups/auth/.*
- ./eclipse-classes/org/jgroups/blocks/.*
- ./eclipse-classes/org/jgroups/blocks/mux/.*
- ./eclipse-classes/org/jgroups/conf/.*
- ./eclipse-classes/org/jgroups/debug/.*
- ./eclipse-classes/org/jgroups/demos/.*
- ./eclipse-classes/org/jgroups/demos/applets/.*
- ./eclipse-classes/org/jgroups/demos/wb/.*
- ./eclipse-classes/org/jgroups/jmx/.*
- ./eclipse-classes/org/jgroups/logging/.*
- ./eclipse-classes/org/jgroups/mux/.*
- ./eclipse-classes/org/jgroups/persistence/.*
- ./eclipse-classes/org/jgroups/protocols/.*
- ./eclipse-classes/org/jgroups/protocols/pbcast/.*
- ./eclipse-classes/org/jgroups/stack/.*
- ./eclipse-classes/org/jgroups/tests/.*
- ./eclipse-classes/org/jgroups/tests/perf/.*
- ./eclipse-classes/org/jgroups/tests/perf/transports/.*
- ./eclipse-classes/org/jgroups/util/.*
- ./lib/.*
- ./lib/licenses/.*
- ./tests/.*
- ./tests/junit/.*
- ./tests/junit/org/.*
- ./tests/junit/org/jgroups/.*
- ./tests/junit/org/jgroups/blocks/.*
- ./tests/junit/org/jgroups/protocols/.*
- ./tests/junit/org/jgroups/tests/.*
- ./tests/junit-functional/.*
- ./tests/junit-functional/org/.*
- ./tests/junit-functional/org/jgroups/.*
- ./tests/junit-functional/org/jgroups/blocks/.*
- ./tests/junit-functional/org/jgroups/protocols/.*
- ./tests/junit-functional/org/jgroups/tests/.*
- ./tests/other/.*
- ./tests/other/org/.*
- ./tests/other/org/jgroups/.*
- ./tests/other/org/jgroups/tests/.*
- ./tests/perf/.*
- ./tests/perf/org/.*
- ./tests/perf/org/jgroups/.*
- ./tests/perf/org/jgroups/tests/.*
- ./tests/perf/org/jgroups/tests/perf/.*
- ./tests/perf/org/jgroups/tests/perf/transports/.*
- ./tests/stress/.*
- ./tests/stress/org/.*
- ./tests/stress/org/jgroups/.*
- ./tests/stress/org/jgroups/tests/.*
